# 当启动 WSL 分发时自动挂载 Windows 驱动器
[automount]

# 设置为 true 会自动挂载固定驱动器（C:/ 或 D:/），使用 DrvFs 挂载到上面设置的根目录下
# 设置为 false 表示驱动器不会自动挂载，需要手动挂载或使用 fstab
enabled=true

# 设置固定驱动器自动挂载的目录
# 此示例更改挂载位置，因此 C 盘会在 /c，而不是默认的 /mnt/c
root = /

# 可以指定 DrvFs 特定选项
# metadata: 启用元数据支持
# uid/gid: 设置文件所有者
# umask: 设置默认权限掩码（目录）
# fmask: 设置文件权限掩码
# case: 大小写敏感设置
options = "metadata,uid=1003,gid=1003,umask=077,fmask=11,case=off"

# 设置在 WSL 分发启动时处理 `/etc/fstab` 文件
mountFsTab=true

# 网络主机设置，启用 WSL 2 使用的 DNS 服务器
# 此示例更改主机名，将 generateHosts 设置为 false，阻止 WSL 自动生成 /etc/hosts
# 将 generateResolvConf 设置为 false，阻止 WSL 自动生成 /etc/resolv.conf
# 这样你可以创建自己的配置（例如：nameserver 1.1.1.1）
[network]
hostname=DemoHost
generateHosts=false
generateResolvConf=false

# 设置 WSL 是否支持互操作进程，如启动 Windows 应用和添加路径变量
# 将这些设置为 false 会阻止启动 Windows 进程和添加 $PATH 环境变量
[interop]
enabled=false
appendWindowsPath=false

# 设置使用 WSL 启动分发时的用户
[user]
default=DemoUser

# 设置新 WSL 实例启动时运行的命令
# 此示例启动 Docker 容器服务
[boot]
command=service docker start